/// Minimal [Declaration] fixture used by adapter tests that only care about
/// round-tripping a payload. The values are plausible but not legally valid.
library;

import 'package:aduanext_domain/domain.dart';

/// Fully-populated [Declaration] that exercises every optional field and
/// every sub-entity in the adapter's JSON serializer. Useful for driving
/// coverage through `_declarationToJson` branches without setting up a real
/// DUA.
Declaration buildRichDeclaration() {
  return Declaration(
    id: 7,
    version: 2,
    typeOfDeclaration: 'EX',
    generalProcedureCode: '1',
    typeOfTransitDocumentCode: 'T1',
    officeOfDispatchExportCode: '001',
    declarationFlow: 'ROAD',
    exporterCode: '310100580824',
    consigneeCode: 'CNS',
    consigneeName: 'Consignee Inc',
    consigneeAddress: '1 Main St',
    declarantCode: '310100975830',
    declarantReferenceNumber: 'REF-1',
    shippingAgentCode: 'SH-1',
    cargoHandlerCode: 'CH-1',
    consignmentReference: 'CONS-1',
    comments: 'note',
    beneficiaryCode: 'BEN',
    beneficiaryName: 'Beneficiary Co',
    beneficiaryAddress: '2 Side St',
    natureOfTransactionCode1: '1',
    natureOfTransactionCode2: '1',
    documentsReceived: true,
    identityOfMeansOfTransportAtBorder: 'ABC-111',
    nationalityOfMeansOfTransportAtBorderCode: 'CR',
    modeOfTransportAtBorderCode: '3',
    identityOfMeansOfTransportAtDepartureOrArrival: 'ABC-222',
    nationalityOfMeansOfTransportAtArrivalDepartureCode: 'CR',
    officeOfEntryCode: '002',
    inlandModeOfTransportCode: '3',
    locationOfGoodsCode: 'LOC-1',
    bankCode: 'BNK',
    bankBranchCode: '01',
    bankAccountNumber: '1234',
    warehouseCode: 'WH1',
    previousCompanyCode: 'PC1',
    originWarehouseForTransferCode: 'WHO',
    shipping: const Shipping(
      tradingCountryCode: 'US',
      countryOfExportCode: 'CR',
      countryOfDestinationCode: 'US',
      countryOfOriginCode: 'CR',
      countryOfLastConsignmentCode: 'CR',
      placeOfLoadingCode: 'CRSJO',
      placeOfLoadingCountryCode: 'CR',
      deliveryTermsCode: 'FOB',
      deliveryTermsPlace: 'SJO',
      deliveryTermsSituationCode: '1',
      countryOfDestinationRegionCode: 'FL',
      countryOfExportRegionCode: 'SJ',
    ),
    transit: const Transit(
      principalCode: 'PC',
      principalRepresentative: 'PR',
      transitDate: '2026-04-13',
      transitPlace: 'SJO',
      transitOfficeOfDestinationCode: '005',
      transitCountryOfDestinationCode: 'NI',
      transitTimeLimit: 'P2D',
      guaranteeReferenceCode: 'G1',
      trucksNumber: '2',
    ),
    sadValuation: const SadValuation(
      invoiceRegime: 'SINGLE_INVOICE',
      totalAmountOfAddedCosts: 100,
      totalAmountOfCostInsuranceFreight: 1200,
      invoiceAmountInForeignCurrency: 1000,
      invoiceCurrencyCode: 'USD',
      invoiceCurrencyExchangeRate: 520.5,
      invoiceAmountInNationalCurrency: 520500,
      externalFreightAmountInForeignCurrency: 100,
      externalFreightCurrencyCode: 'USD',
      externalFreightCurrencyExchangeRate: 520.5,
      internalFreightAmountInForeignCurrency: 20,
      internalFreightCurrencyCode: 'CRC',
      insuranceAmountInForeignCurrency: 10,
      insuranceCurrencyCode: 'USD',
      otherCostsAmountInForeignCurrency: 5,
      otherCostsCurrencyCode: 'USD',
      deductionsAmountInForeignCurrency: 2,
      deductionsCurrencyCode: 'USD',
    ),
    items: const [
      DeclarationItem(
        id: 10,
        version: 1,
        rank: 1,
        commodityCode: '48191000',
        commodityCodeNationalPrecision2: '00',
        commodityCodeNationalPrecision3: '00',
        commodityCodeNationalPrecision4: '00',
        specificationCode: 'SPEC',
        commercialDescription: 'LED grow lights 600W full spectrum',
        invoiceReference: 'SINGLE_INVOICE_REFERENCE',
        invoiceLine: 1,
        itemGrossMass: 10.5,
        netMass: 9.0,
        packageNumber: 2,
        packageMark1: 'MARK1',
        packageMark2: 'MARK2',
        itemPackageTypeCode: 'BX',
        modeOfPayment: 'CASH',
        dutiesAndTaxesAmount: 100.0,
        guaranteedAmount: 50.0,
        procedure: ItemProcedure(
          quota: 'Q1',
          valuationMethodCode: 'M1',
          countryOfOriginRegionCode: 'SJ',
          itemCountryOfOriginCode: 'CR',
          extendedProcedureCode: '1000',
          nationalProcedureCode: '000',
          processingProgramsProductCode: 'PPC',
          previousDocument: PreviousDocument(
            previousCustomsOffice: '001',
            previousRegistrationNumber: '9999',
            previousRegistrationSerial: 'A',
            previousRegistrationYear: '2025',
            previousItemRank: '1',
          ),
        ),
        itemValuation: ItemValuation(
          itemInvoiceAmountInForeignCurrency: 500,
          itemInvoiceCurrencyCode: 'USD',
          itemInvoiceCurrencyExchangeRate: 520.5,
          itemInvoiceAmountInNationalCurrency: 260250,
          statisticalValue: 260250,
          costInsuranceFreightAmount: 600,
          marketValueAmount: 650,
          marketValueRate: 1.1,
          marketValueCurrencyCode: 'USD',
          marketValueBasisDescription: 'comparable',
          marketValueBasisAmount: 600,
          itemExternalFreightAmountInForeignCurrency: 50,
          itemInternalFreightAmountInForeignCurrency: 10,
          itemInsuranceAmountInForeignCurrency: 5,
          itemOtherCostsAmountInForeignCurrency: 2,
          itemDeductionsAmountInForeignCurrency: 1,
        ),
        attachedDocuments: [
          AttachedDocument(
            attachedDocCode: '380',
            attachedDocReference: 'INV-1',
            date: '2026-04-01',
            path: '/uploads/inv-1.pdf',
          ),
        ],
        containers: [
          Container(
            containerReference: 'DMOU2459120',
            containerTypeCode: '45VH',
            sealNumber1: 'SEAL1',
            sealingPartyCode: 'SP',
            numberOfPackages: 2,
            emptyFullIndicatorCode: 'F',
          ),
        ],
        vins: ['WVWXYZ1234567890'],
        itemTaxes: [
          ItemTax(
            code: 'IVA',
            description: 'Impuesto al Valor Agregado',
            amount: 13.0,
            baseAmount: 100.0,
            rate: 13.0,
          ),
        ],
      ),
    ],
    invoices: const [
      Invoice(
        invoiceReference: 'SINGLE_INVOICE_REFERENCE',
        workingMode: 'PER_VALUE',
        deliveryTermsCode: 'FOB',
        termsOfPaymentCode: 'CASH',
        exporterName: 'Exporter CR S.A.',
        exporterAddress: 'San Jose',
        invoiceAmountInForeignCurrency: 1000,
        invoiceCurrencyCode: 'USD',
        invoiceCurrencyExchangeRate: 520.5,
        totalAmountOfCostInsuranceFreight: 1200,
      ),
    ],
    globalTaxes: const [
      GlobalTax(
        code: 'PRO',
        description: 'Pago PROCOMER',
        amount: 7.5,
        baseAmount: 1000,
        rate: 0.75,
        manual: true,
        methodOfPayment: 'GUARANTEE',
        benCode: 'BEN',
        benName: 'PROCOMER',
        initAmount: 7.5,
      ),
    ],
    ignoredWarnings: const ['W1', 'W2'],
  );
}

Declaration buildMinimalDeclaration({
  String typeOfDeclaration = 'EX',
  String generalProcedureCode = '1',
  String officeOfDispatchExportCode = '001',
  String exporterCode = '310100580824',
  String declarantCode = '310100975830',
  String officeOfEntryCode = '002',
}) {
  return Declaration(
    typeOfDeclaration: typeOfDeclaration,
    generalProcedureCode: generalProcedureCode,
    officeOfDispatchExportCode: officeOfDispatchExportCode,
    exporterCode: exporterCode,
    declarantCode: declarantCode,
    officeOfEntryCode: officeOfEntryCode,
    natureOfTransactionCode1: '1',
    natureOfTransactionCode2: '1',
    documentsReceived: true,
    shipping: const Shipping(countryOfExportCode: 'CR'),
    sadValuation: const SadValuation(),
    items: const [
      DeclarationItem(
        rank: 1,
        commercialDescription: 'LED grow lights 600W full spectrum',
        procedure: ItemProcedure(
          itemCountryOfOriginCode: 'CR',
          extendedProcedureCode: '1000',
        ),
        itemValuation: ItemValuation(),
      ),
    ],
  );
}
